### ISSUE TITLE
request to add avoid recording rerun

### ISSUE THREAD

**Issue by Kioriky** [cmd430/twitch-stream-recorder#1]
all work great in my case, but if you add options to avoid recording rerun, this will be great twitch recorder

**Comment by cmd430** [comment]
i don't think the PubSub endpoint has the required information on it, so this would require querying the Twitch API, this can take up to 5mins to update to even show the stream is live so unfortunately i wont be adding the feature, however if it becomes possible i will happily add an option for this

**Comment by Kioriky** [comment]
ok, thanks for reply
